---
title: "dev_fastdash"
author: "Will Schulz"
date: "4/30/2022"
output: html_document
---

```{r}
library(tricordR)

```


```{r}
study_name <- "spirals_bad_pilot"
participant_panel <- "participants"
assignment_panel <- "assignments"

#test <- prep_network_data_d3_spirals(study_name,participant_group,assignment_group, include_protected = F)

test <- prep_network_data_d3(study_name, participant_panel, assignment_panel)


test <- prep_network_data_d3_spirals(study_name, participant_panel, assignment_panel)
```


```{r}
prep_network_data_d3_spirals_test <- function(study_name, panel_name, assignment_panel = "assignments", include_protected = TRUE){
message("Loading id_links ...")
  id_links <- dir(paste0("~/tricordings/studies/", study_name, "/", panel_name, "/id_links_confirmed/"), full.names = T) %>% map_dfr(., readRDS)# %>% filter(ResponseId != "R_3fO7aQmR13LJ4zs") #target - remember to remove this filter and simply prevent duplicates in future
  id_links <- id_links[!duplicated(id_links$ResponseId, fromLast = T),]
message("Loading p_friends_all ...")
  p_friends_all <- dir(paste0("~/tricordings/studies/", study_name, "/", panel_name, "/twitter_scrapes/friends/"), full.names = T) %>% map_dfr(., readRDS)

  if (nrow(p_friends_all)==0) {p_friends_all <- dir(paste0("~/tricordings/studies/", "/", study_name, "/", panel_name, "/twitter_scrapes/first_friends/"), full.names = T)[1] %>% map_dfr(., readRDS)}


  relevant_user_ids <- unique(id_links$user_id) %>% .[which(!is.na(.))]# %>% .[which(! . %in% unique(p_friends_all$user))]

  if (include_protected){
    message("Loading include_protected ...")
    a_followers_relevant <- dir(paste0("~/tricordings/studies/", study_name, "/", assignment_panel, "/twitter_scrapes/followers/"), full.names = T) %>% map_dfr(., readRelevantAssignmentFollowers, relevant_user_ids = relevant_user_ids)
    protected_relevant_friends <- a_followers_relevant %>% transmute(userx = user_id, user_idx = user, scraped_at) %>% rename("user" = userx, "user_id" = user_idx)
    p_friends_all <- rbind(p_friends_all, protected_relevant_friends)
  }
    message("Loading par_info ...")
  par_info <- dir(paste0("~/tricordings/studies/", study_name, "/", panel_name, "/twitter_scrapes/user_info/"), full.names = T) %>% map_dfr(readRDS) %>% arrange(desc(created_at)) %>% distinct(user_id, .keep_all = T) %>% mutate(group = "participant") %>% filter(user_id %in% id_links$user_id)
  message("Loading ass_info ...")
  ass_info <- dir(paste0("~/tricordings/studies/", study_name, "/", assignment_panel, "/twitter_scrapes/user_info/"), full.names = T) %>% map_dfr(readRDS) %>% arrange(desc(created_at)) %>% distinct(user_id, .keep_all = T) %>% mutate(group = "assignment")
  all_info <- rbind(par_info, ass_info)

  message("Loading survey_responses ...")
  survey_responses <- prep_survey_data(paste0("~/tricordings/studies/", study_name, "/"), panel_name)[[1]] %>% distinct(ResponseId, .keep_all = T) %>% filter(twitter_agreement=="Yes")# %>% filter(ResponseId != "R_3fO7aQmR13LJ4zs") #target - remember to remove this filter and simply prevent duplicates in future
  vertex_metadata <- id_links %>% select(ResponseId, start_date, shown, claimed, user_id) %>% left_join(., survey_responses %>% select(-c(shown, claimed, user_id)), by="ResponseId") %>% full_join(., all_info)
  #vertex_metadata <- all_info

  na_user_ids_indices <- which(is.na(vertex_metadata$user_id))
  for(i in 1:length(na_user_ids_indices)){
    vertex_metadata$user_id[na_user_ids_indices[i]] <- paste0("UNMATCHED_",i)
    vertex_metadata$screen_name[na_user_ids_indices[i]] <- paste0("UNMATCHED_",i)
  }

  vertex_metadata$stroke_group <- "none"
  vertex_metadata$stroke_group[na_user_ids_indices] <- "unmatched"
  vertex_metadata$stroke_group[which(vertex_metadata$protected)] <- "protected"

  vertex_metadata$stroke_color <- "white"
  vertex_metadata$stroke_color[na_user_ids_indices] <- "red"
  vertex_metadata$stroke_color[which(vertex_metadata$protected)] <- "orange"

  vertex_metadata$group[which(vertex_metadata$t==1)] <- "treated"
  vertex_metadata$group[which(vertex_metadata$t==0)] <- "placeboed"

  p_friends_all <- left_join(p_friends_all, (vertex_metadata %>% select(user_id, start_date)), by = c("user" = "user_id"))

  data <- p_friends_all %>%
    filter(user_id %in% vertex_metadata$user_id) %>%
    group_by(user, user_id) %>%
    summarise(first = min(scraped_at),
              last = max(scraped_at),
              start_date = start_date[1]
              # color = ifelse(difftime(Sys.time(), last, units = "day")>1,
              #                "orange",
              #                "green")
    ) %>%
    mutate(color = case_when((difftime(Sys.time(), last, units = "day")>1) ~ "orange",
                             ((difftime(Sys.time(), last, units = "day")<=1) & difftime(first, start_date, units = "day")>=0) ~ "green",
                             (difftime(first, start_date, units = "day")<0) ~ "blue")) %>% select(-start_date)


  #always-inactive claims should be red:
  data <- map_dfr(which((vertex_metadata$group!="assignment") & (sapply(vertex_metadata$claimed, length)>0)),
                  ~data.frame("user" = vertex_metadata$user_id[.x],
                              "user_id" = vertex_metadata$claimed[[.x]],
                              first = as.POSIXct(NA), last = as.POSIXct(NA), color = "red")) %>%
    anti_join(., data, by = c("user", "user_id")) %>%
    rbind(., data)

  #shown and not claimed should be gray
  data <- map_dfr(which(vertex_metadata$group!="assignment"),
                  ~data.frame("user" = vertex_metadata$user_id[.x],
                              "user_id" = vertex_metadata$shown[[.x]],
                              first = as.POSIXct(NA), last = as.POSIXct(NA), color = "gray")) %>%
    anti_join(., data, by = c("user", "user_id")) %>%
    rbind(., data)

  return(list("e" = data, "v" = vertex_metadata))
}


```


```{r}
test <- prep_network_data_d3_spirals_test(study_name, participant_panel, assignment_panel)

test <- prep_network_data_d3_spirals_test(study_name, participant_panel, assignment_panel, include_protected = F)

test <- prep_network_data_d3_spirals(study_name, participant_panel, assignment_panel, include_protected = F)

length(test$v)

test2 <- prep_network_data_d3_spirals(study_name, participant_panel, assignment_panel, include_protected = T)
```


```{r}
test[[2]] %>% select(ResponseId, user_id, screen_name, group)
myNodes <- test$v %>% add_column(NodeID = 1:nrow(.)-1, .before = 0)
myLinks <- test$e %>% mutate("source" = nodeIndexer(user, myNodes),
                                 "target" = nodeIndexer(user_id, myNodes),
                                 "value" = 2
    )
```


```{r}
assignment_node_col <- "gray40"
placeboed_node_col <- "plum"
treated_node_col <- "dodgerblue2"

MyClickScript <- "Shiny.setInputValue('user_text', d.name);"

fn <- networkD3::forceNetwork(Links = myLinks, Nodes = myNodes, Value = "value", Source = "source", Target = "target", NodeID = "screen_name", Group = "group", opacity = 1, arrows = T, fontSize = 20, fontFamily = "helvetica", legend=T,
                 linkColour = myLinks$color, charge = -10, zoom = F, linkDistance = 80, clickAction = MyClickScript, bounded = T,
                 colourScale = paste0("d3.scaleOrdinal().domain(['assignment','placeboed','treated']).range([",
                                      paste0("\'",paste(gplots::col2hex(c(assignment_node_col,
                                                                          placeboed_node_col,
                                                                          treated_node_col)),
                                                        collapse = "\', \'"),"\'")
                                      ,"]);"))

```



```{r}
assignment_node_col <- "gray40"
placeboed_node_col <- "plum"
treated_node_col <- "dodgerblue2"
fn <- networkD3::forceNetwork(Links = myLinks, Nodes = myNodes, Value = "value", Source = "source", Target = "target", NodeID = "screen_name", Group = "group", opacity = 1, arrows = T, fontSize = 20, fontFamily = "helvetica", legend=T,
                 linkColour = myLinks$color, charge = -10, zoom = F, linkDistance = 80, bounded = T,
                 colourScale = paste0("d3.scaleOrdinal().domain(['assignment','placeboed','treated']).range([",
                                      paste0("\'",paste(gplots::col2hex(c(assignment_node_col,
                                                                          placeboed_node_col,
                                                                          treated_node_col)),
                                                        collapse = "\', \'"),"\'")
                                      ,"]);"))
fn
```


```{r}
assignment_node_col <- "gray40"
placeboed_node_col <- "plum"
treated_node_col <- "dodgerblue2"
fn <- networkD3::forceNetwork(Links = myLinks, Nodes = myNodes, Value = "value", Source = "source", Target = "target", NodeID = "screen_name", Group = "group", opacity = 1, arrows = T, fontSize = 20, fontFamily = "helvetica", legend=T,
                 linkColour = myLinks$color, charge = -10, zoom = F, linkDistance = 80, bounded = T,
                 colourScale = paste0("d3.scaleOrdinal().domain(['assignment','placeboed','treated']).range([",
                                      paste0("\'",paste(gplots::col2hex(c(assignment_node_col,
                                                                          placeboed_node_col,
                                                                          treated_node_col)),
                                                        collapse = "\', \'"),"\'")
                                      ,"]);"))
fn$x$nodes$border <- myNodes$stroke_color

fn
```



```{r}
assignment_node_col <- "gray40"
placeboed_node_col <- "plum"
treated_node_col <- "dodgerblue2"
fn <- networkD3::forceNetwork(Links = myLinks, Nodes = myNodes, Value = "value", Source = "source", Target = "target", NodeID = "screen_name", Group = "group", opacity = 1, arrows = T, fontSize = 20, fontFamily = "helvetica", legend=T,
                 linkColour = myLinks$color, charge = -10, zoom = F, linkDistance = 80, bounded = T,
                 colourScale = paste0("d3.scaleOrdinal().domain(['assignment','placeboed','treated']).range([",
                                      paste0("\'",paste(gplots::col2hex(c(assignment_node_col,
                                                                          placeboed_node_col,
                                                                          treated_node_col)),
                                                        collapse = "\', \'"),"\'")
                                      ,"]);"))
fn$x$nodes$border <- myNodes$stroke_color
fn <- htmlwidgets::onRender(fn,
                                'function(el, x) { d3.selectAll("circle").style("stroke", d => d.border); }')
fn
```




```{r}
prep_network_data_d3_spirals <- function(study_name, panel_name, assignment_panel = "assignments", include_protected = TRUE, verbose = TRUE){

  if(verbose){message("Loading id_links ...")}
  id_links <- dir(paste0("~/tricordings/studies/", study_name, "/", panel_name, "/id_links_confirmed/"), full.names = T) %>% map_dfr(., readRDS)# %>% filter(ResponseId != "R_3fO7aQmR13LJ4zs") #target - remember to remove this filter and simply prevent duplicates in future
  id_links <- id_links[!duplicated(id_links$ResponseId, fromLast = T),]
  if(verbose){message("nrow id_links: ", nrow(id_links))}

  p_friends_all <- dir(paste0("~/tricordings/studies/", study_name, "/", panel_name, "/twitter_scrapes/friends/"), full.names = T) %>% map_dfr(., readRDS)

  if (nrow(p_friends_all)==0) {p_friends_all <- dir(paste0("~/tricordings/studies/", "/", study_name, "/", panel_name, "/twitter_scrapes/first_friends/"), full.names = T)[1] %>% map_dfr(., readRDS)}


  relevant_user_ids <- unique(id_links$user_id) %>% .[which(!is.na(.))]# %>% .[which(! . %in% unique(p_friends_all$user))]

  if (include_protected){
    a_followers_relevant <- dir(paste0("~/tricordings/studies/", study_name, "/", assignment_panel, "/twitter_scrapes/followers/"), full.names = T) %>% map_dfr(., readRelevantAssignmentFollowers, relevant_user_ids = relevant_user_ids)
    protected_relevant_friends <- a_followers_relevant %>% transmute(userx = user_id, user_idx = user, scraped_at) %>% rename("user" = userx, "user_id" = user_idx)
    p_friends_all <- rbind(p_friends_all, protected_relevant_friends)
  }

  par_info <- dir(paste0("~/tricordings/studies/", study_name, "/", panel_name, "/twitter_scrapes/user_info/"), full.names = T) %>% map_dfr(readRDS) %>% arrange(desc(created_at)) %>% distinct(user_id, .keep_all = T) %>% mutate(group = "participant") %>% filter(user_id %in% id_links$user_id)
  ass_info <- dir(paste0("~/tricordings/studies/", study_name, "/", assignment_panel, "/twitter_scrapes/user_info/"), full.names = T) %>% map_dfr(readRDS) %>% arrange(desc(created_at)) %>% distinct(user_id, .keep_all = T) %>% mutate(group = "assignment")
  all_info <- rbind(par_info, ass_info)

  survey_responses <- prep_survey_data(paste0("~/tricordings/studies/", study_name, "/"), panel_name)[[1]] %>% distinct(ResponseId, .keep_all = T) %>% filter(twitter_agreement=="Yes")# %>% filter(ResponseId != "R_3fO7aQmR13LJ4zs") #target - remember to remove this filter and simply prevent duplicates in future
  vertex_metadata <- id_links %>% select(ResponseId, start_date, shown, claimed, user_id) %>% left_join(., survey_responses %>% select(-c(shown, claimed, user_id)), by="ResponseId") %>% full_join(., all_info)
  #vertex_metadata <- all_info

  na_user_ids_indices <- which(is.na(vertex_metadata$user_id))
  for(i in 1:length(na_user_ids_indices)){
    vertex_metadata$user_id[na_user_ids_indices[i]] <- paste0("UNMATCHED_",i)
    vertex_metadata$screen_name[na_user_ids_indices[i]] <- paste0("UNMATCHED_",i)
  }

  vertex_metadata$stroke_group <- "none"
  vertex_metadata$stroke_group[na_user_ids_indices] <- "unmatched"
  vertex_metadata$stroke_group[which(vertex_metadata$protected)] <- "protected"

  vertex_metadata$stroke_color <- "white"
  vertex_metadata$stroke_color[na_user_ids_indices] <- "red"
  vertex_metadata$stroke_color[which(vertex_metadata$protected)] <- "orange"

  vertex_metadata$group[which(vertex_metadata$t==1)] <- "treated"
  vertex_metadata$group[which(vertex_metadata$t==0)] <- "placeboed"

  p_friends_all <- left_join(p_friends_all, (vertex_metadata %>% select(user_id, start_date)), by = c("user" = "user_id"))

  data <- p_friends_all %>%
    filter(user_id %in% vertex_metadata$user_id) %>%
    group_by(user, user_id) %>%
    summarise(first = min(scraped_at),
              last = max(scraped_at),
              start_date = start_date[1]
              # color = ifelse(difftime(Sys.time(), last, units = "day")>1,
              #                "orange",
              #                "green")
    ) %>%
    mutate(color = case_when((difftime(Sys.time(), last, units = "day")>1) ~ "orange",
                             ((difftime(Sys.time(), last, units = "day")<=1) & difftime(first, start_date, units = "day")>=0) ~ "green",
                             (difftime(first, start_date, units = "day")<0) ~ "blue")) %>% select(-start_date)


  #always-inactive claims should be red:
  data <- map_dfr(which((vertex_metadata$group!="assignment") & (sapply(vertex_metadata$claimed, length)>0)),
                  ~data.frame("user" = vertex_metadata$user_id[.x],
                              "user_id" = vertex_metadata$claimed[[.x]],
                              first = as.POSIXct(NA), last = as.POSIXct(NA), color = "red")) %>%
    anti_join(., data, by = c("user", "user_id")) %>%
    rbind(., data)

  #shown and not claimed should be gray
  data <- map_dfr(which(vertex_metadata$group!="assignment"),
                  ~data.frame("user" = vertex_metadata$user_id[.x],
                              "user_id" = vertex_metadata$shown[[.x]],
                              first = as.POSIXct(NA), last = as.POSIXct(NA), color = "gray")) %>%
    anti_join(., data, by = c("user", "user_id")) %>%
    rbind(., data)
  if(verbose){message("nrow e: ", nrow(data))}
  if(verbose){message("nrow v: ", nrow(vertex_metadata))}

  return(list("e" = data, "v" = vertex_metadata))
}

test <- prep_network_data_d3_spirals(study_name, participant_panel, assignment_panel, include_protected = F)

length(test)

```






# Timeline Dash D3

## Fix Bug

Error in data.frame: arguments imply differing number of rows: 132323, 0, 1

```{r}
#original
prep_timeline_data(panel_directory = paste0(experiment_directory(), panels()[1]),
                       sessions_back=(input$days_back),
                       include_historical = input$include_historical,
                       load_all_since_first = input$load_all_since_first)

```


```{r}
#nonreactive
experiment_directory = "~/tricordings/studies/spirals_bad_pilot/"
panels = c("participants", "assignments")
days_back = 50
include_historical = F
load_all_since_first = F

test <- prep_timeline_data(panel_directory = paste0(experiment_directory, panels[1]),
                       sessions_back=(days_back),
                       include_historical = include_historical,
                       load_all_since_first = load_all_since_first)

test
dim(test[[1]])

nrow(test[[1]])
```


```{r}

test[[1]] <- test[[1]] %>% filter(created_at > (Sys.time() - 60*60*24*days_back))


data <- data.frame(x = (1000*as.numeric(test[[1]]$created_at)),
                   y = test[[1]]$user_index,
                   text = test[[1]]$text,
                   sentiment = test[[1]]$score,
                   screen_name = test[[1]]$screen_name,
                   created_at = test[[1]]$created_at,
                   size = rep(4, nrow(test[[1]])))

!is.null(test$score)

if_else(!is.null(test$score), true = test[[1]]$score, false = NA)

ifelse(!is.null(test$score), yes = test[[1]]$score, no = NA)

data <- data.frame(x = (1000*as.numeric(test[[1]]$created_at)),
               y = test[[1]]$user_index,
               text = test[[1]]$text,
               sentiment = ifelse(!is.null(test$score), yes = test[[1]]$score, no = NA),
               screen_name = test[[1]]$screen_name,
               created_at = test[[1]]$created_at,
               size = 4)

data <- data.frame(x = (1000*as.numeric(test[[1]]$created_at)),
               y = test[[1]]$user_index,
               text = test[[1]]$text,
               sentiment = test[[1]]$score,
               screen_name = test[[1]]$screen_name,
               created_at = test[[1]]$created_at,
               size = rep(4, nrow(test[[1]])))

data <- data.frame(x = (1000*as.numeric(test[[1]]$created_at)),
               y = test[[1]]$user_index,
               text = test[[1]]$text,
               sentiment = test[[1]]$score,
               screen_name = test[[1]]$screen_name,
               created_at = test[[1]]$created_at)
```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```




# Make Fast With Buffer




```{r}
#this is pretty fast, unclear why it doesn't work in the dashboard
experiment_directory = "~/tricordings/studies/spirals_bad_pilot/"
panels = c("participants", "assignments")
days_back = 50
include_historical = T
load_all_since_first = T

timeline_data <- prep_timeline_data(panel_directory = paste0(experiment_directory, panels[1]),
                       sessions_back=(days_back),
                       include_historical = include_historical,
                       load_all_since_first = load_all_since_first)

```


```{r}


```


```{r}


```


```{r}


```


```{r}


```



