---
title: "diagnosing network dash"
author: "Will Schulz"
date: "5/16/2022"
output: html_document
---

```{r}
library(tricordR)

```


```{r}
verbose = TRUE
include_protected <- FALSE

```


```{r}
tricordings_directory <- "~/tricordings/studies/"

#study_name <- "spirals_bad_pilot"
study_name <- "spirals_experiment"
participant_panel <- "participants"
assignment_panel <- "assignments"

panel_name <- participant_panel
```


```{r}
test <- prep_network_data_d3_spirals(study_name, participant_panel, assignment_panel, include_protected = F)


test

test[[2]]
```


```{r}

    if (verbose) {
        message("Test message ...")
    }
    if (verbose) {
        message("Loading id_links ...")
    }
    id_links <- dir(paste0("~/tricordings/studies/", study_name, 
        "/", panel_name, "/id_links_confirmed/"), full.names = T) %>% 
        map_dfr(., readRDS)
    id_links <- id_links[!duplicated(id_links$ResponseId, fromLast = T), 
        ]
    if (verbose) {
        message("nrow id_links: ", nrow(id_links))
    }
    message("Loading all participants' friends...")
    p_friends_all <- dir(paste0("~/tricordings/studies/", study_name, 
        "/", panel_name, "/twitter_scrapes/friends/"), full.names = T) %>% 
        map_dfr(., readRDS)
    if (nrow(p_friends_all) == 0) {
        p_friends_all <- dir(paste0("~/tricordings/studies/", 
            "/", study_name, "/", panel_name, "/twitter_scrapes/first_friends/"), 
            full.names = T)[1] %>% map_dfr(., readRDS)
    }
    message("Selecting relevant user_ids ...")
    relevant_user_ids <- unique(id_links$user_id) %>% .[which(!is.na(.))]
    if (include_protected) {
        message("Including protected accounts ...")
        a_followers_relevant <- dir(paste0("~/tricordings/studies/", 
            study_name, "/", assignment_panel, "/twitter_scrapes/followers/"), 
            full.names = T) %>% map_dfr(., readRelevantAssignmentFollowers, 
            relevant_user_ids = relevant_user_ids)
        protected_relevant_friends <- a_followers_relevant %>% 
            transmute(userx = user_id, user_idx = user, scraped_at) %>% 
            rename(user = userx, user_id = user_idx)
        p_friends_all <- rbind(p_friends_all, protected_relevant_friends)
    }
    par_info <- dir(paste0("~/tricordings/studies/", study_name, 
        "/", panel_name, "/twitter_scrapes/user_info/"), full.names = T) %>% 
        map_dfr(readRDS) %>% arrange(desc(created_at)) %>% distinct(user_id, 
        .keep_all = T) %>% mutate(group = "participant") %>% 
        filter(user_id %in% id_links$user_id)
    ass_info <- dir(paste0("~/tricordings/studies/", study_name, 
        "/", assignment_panel, "/twitter_scrapes/user_info/"), 
        full.names = T) %>% map_dfr(readRDS) %>% arrange(desc(created_at)) %>% 
        distinct(user_id, .keep_all = T) %>% mutate(group = "assignment")
    all_info <- rbind(par_info, ass_info)
    message("Loading survey responses ...")
    survey_responses <- prep_survey_data(paste0("~/tricordings/studies/", 
        study_name, "/"), panel_name)[[1]] %>% distinct(ResponseId, 
        .keep_all = T) %>% filter(str_detect(twitter_agreement, "Yes"))#change 1
    message("Setting vertex metadata ...")
    vertex_metadata <- id_links %>% select(ResponseId, start_date, 
        shown, claimed, user_id) %>% left_join(., survey_responses %>% 
        select(-c(start_date, end_date, shown, claimed, user_id)), by = "ResponseId") %>%  #change 2
        full_join(., all_info)
    na_user_ids_indices <- which(is.na(vertex_metadata$user_id))
    for (i in 1:length(na_user_ids_indices)) {
        vertex_metadata$user_id[na_user_ids_indices[i]] <- paste0("UNMATCHED_", 
            i)
        vertex_metadata$screen_name[na_user_ids_indices[i]] <- paste0("UNMATCHED_", 
            i)
    }
    vertex_metadata$stroke_group <- "none"
    vertex_metadata$stroke_group[na_user_ids_indices] <- "unmatched"
    vertex_metadata$stroke_group[which(vertex_metadata$protected)] <- "protected"
    vertex_metadata$stroke_color <- "white"
    vertex_metadata$stroke_color[na_user_ids_indices] <- "red"
    vertex_metadata$stroke_color[which(vertex_metadata$protected)] <- "orange"
    #vertex_metadata$group[which(vertex_metadata$t == 1)] <- "treated"
    #vertex_metadata$group[which(vertex_metadata$t == 0)] <- "placeboed"
    message("Joining participant friends to vertext metadata ...")
    p_friends_all <- left_join(p_friends_all, (vertex_metadata %>% 
        select(user_id, start_date)), by = c(user = "user_id"))
    message("Generating data object ...")
    data <- p_friends_all %>% filter(user_id %in% vertex_metadata$user_id) %>% 
        group_by(user, user_id) %>% summarise(first = min(scraped_at), 
        last = max(scraped_at), start_date = start_date[1]) %>% 
        mutate(color = case_when((difftime(Sys.time(), last, 
            units = "day") > 1) ~ "orange", ((difftime(Sys.time(), 
            last, units = "day") <= 1) & difftime(first, start_date, 
            units = "day") >= 0) ~ "green", (difftime(first, 
            start_date, units = "day") < 0) ~ "blue")) %>% select(-start_date)
    data <- map_dfr(which((vertex_metadata$group != "assignment") & 
        (sapply(vertex_metadata$claimed, length) > 0)), ~data.frame(user = vertex_metadata$user_id[.x], 
        user_id = vertex_metadata$claimed[[.x]], first = as.POSIXct(NA), 
        last = as.POSIXct(NA), color = "red")) %>% anti_join(., 
        data, by = c("user", "user_id")) %>% rbind(., data)
    data <- map_dfr(which(vertex_metadata$group != "assignment"), 
        ~data.frame(user = vertex_metadata$user_id[.x], user_id = vertex_metadata$shown[[.x]], 
            first = as.POSIXct(NA), last = as.POSIXct(NA), color = "gray")) %>% 
        anti_join(., data, by = c("user", "user_id")) %>% rbind(., 
        data)
    message("Finished prepping network data!")

```


# make id_links_confirmed

```{r}
id_links_bound <- dir("~/tricordings/studies/spirals_experiment/participants/id_links/", full.names = T) %>% map_dfr(., readRDS)
id_links_bound <- id_links_bound %>% rename(qualtrics_start_date = start_date, qualtrics_end_date = end_date)
id_links_bound
```


for each na user_id row, 
in order starting with the row whose best candidate has the largest number of matches,
filter out all user_ids already matched from the candidate df,
if zero remain, flag as noncompliant
if exactly one remains, set that as the row's user_id,
if more than one remains, flag as ambiguous


```{r}
matched_userids <- id_links_bound %>% filter(!is.na(user_id)) %>% pull(user_id)

unmatched <- id_links_bound %>% filter(is.na(user_id))
unmatched

```


```{r}
unmatched$candidates
nrow(unmatched$candidates)

test <- unmatched$candidates[[2]]

max(test$match_count)

maxMatch <- function(x){
  return(max(x$match_count))
}

lapply(unmatched$candidates, nrow)
lapply(unmatched$candidates, maxMatch)

nonDupMatchCount <- function(x, already_matched){
  return(x %>% filter(!follower %in% already_matched) %>% nrow())
}

nonDupMatches <- function(x, already_matched){
  return(x %>% filter(!follower %in% already_matched) %>% pull(follower))
}

lapply(unmatched$candidates, nonDupMatches, already_matched = matched_userids)


sapply(unmatched$candidates, maxMatch)
sapply(unmatched$candidates, nonDupMatchCount, already_matched = matched_userids)
sapply(unmatched$candidates, nonDupMatches, already_matched = matched_userids)
```


```{r}


```


```{r}


```


```{r}
id_links_confirmed <- id_links_bound %>% filter(!is.na(user_id))
#saveRDS(id_links_confirmed, file = paste0("~/tricordings/studies/spirals_experiment/participants/id_links_confirmed/id_links",timeCode(),".rds"))

```


```{r}


```



```{r}
id_links_test <- dir("~/tricordings/studies/spirals_experiment/participants/id_links/", full.names = T)[1] %>% map_dfr(., readRDS)
id_links_test
```



```{r}
id_links

```


```{r}
survey_responses %>% select(start_date)

```


# do sentiment classification bc why not

```{r}
library("sentimentr")

```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


