---
title: "sampler dev"
author: "Will Schulz"
date: "7/7/2021"
output: html_document
---

```{r}
library(tricordR)
```


```{r}
tokens <- prepTokens("ws_tw", 1:9)

```



```{r}
user_ids <- c()
rl <- rate_limit(tokens[[1]])

which(rl$limit != rl$remaining)


rl
```


```{r}
#sampling 

start <- Sys.time()
while (as.numeric(difftime(Sys.time(), start, units = "mins")) < 5){
  print(paste0(round(as.numeric(difftime(Sys.time(), start, units = "mins")), 2), " mins elapsed"))
  streamed_tweets <- NULL
  erred <- FALSE
  warned <- FALSE
  error_text <- "No error"
  warning_text <- "No warning"
  tryCatch({streamed_tweets <- stream_tweets(timeout = 10, token = tokens[[1]])},
           error=function(e) {error_text <<- (e$message); erred <<- TRUE},
           warning=function(w) {warning_text <<- (w$message); warned <<- TRUE}
           )

  if(erred){
    message(paste0("Error!\n", error_text,"\nContinuing to sample..."))
    Sys.sleep(5)
    next
  }
  if(warned){
    message(paste0("Warning!\n", warning_text,"\nContinuing to sample..."))
    Sys.sleep(5)
    next
  }
  if(is.null(streamed_tweets)){
    message(paste0("NULL tweets!\nContinuing to sample..."))
    Sys.sleep(5)
    next
  }
  user_ids <- unique(c(user_ids, streamed_tweets %>% filter(lang == "en", followers_count>4999) %>% pull(user_id) %>% unique()))
}

#ran this a few times on 210707 until we had more than 1k
saveRDS(user_ids, file = "sampler_data/user_ids_streamed_210707.rds")
```



```{r}
user_friends <- getFriendsBig(user_ids, list_tokens = tokens)

time_code <- timeCode()

saveRDS(user_friends, file = paste0("~/tricordings/studies/spirals_assignment_sampling/2_friends_scraped/friends_",time_code,".rds"))

head(user_friends)
```


# Friend Getting function

```{r}

study_name = "spirals_assignment_sampling"

getSampledUsersFriends <- function(study_name, n = 1000000, tokens, max_hours){
  time_code <- timeCode()
  sampled <- dir(paste0("~/tricordings/studies/",study_name,"/1_user_ids_streamed"), full.names = T) %>% sapply(., readRDS) %>% unlist(., use.names = F)
  done <- dir(paste0("~/tricordings/studies/",study_name,"/2_friends_scraped"), full.names = T) %>% map_dfr(., readRDS) %>% pull(user) %>% unique
  to_do <- sampled[-which(sampled %in% done)]
  rm(sampled,done)
  new_friends <- getFriendsBig(users = to_do, n = n, list_tokens = tokens, max_hours = max_hours)
  message(paste0(nrow(new_friends), " friends collected from ",length(unique(new_friends$user))," users."))
  if (nrow(new_friends)>0){
    saveRDS(new_friends, file = paste0("~/tricordings/studies/",study_name,"/2_friends_scraped/friends_",time_code,".rds"))
  }
}


getSampledUsersFriends(study_name = "spirals_assignment_sampling", n = 1000000, tokens = tokens, max_hours = .1)
```


```{r}


```


```{r}


```


# Make Barbera scores

```{r}
#estimateIdeology2 GOOD

#read in all friend scrapes so far
friends_df <- dir("~/tricordings/studies/spirals_assignment_sampling/2_friends_scraped", full.names = T) %>% map_dfr(., readRDS)
user_metadata <- lookup_users(users = unique(friends_df$user), token = prepTokens("ws_tw")[[1]])

barbera_scores_list <- list()

pb <- progress::progress_bar$new(format = "  estimating [:bar] :percent eta: :eta", total = nrow(user_metadata), clear = FALSE)
for (i in 1:nrow(user_metadata)) {
  barbera_scores_list[[i]] <- NA
  try(barbera_scores_list[[i]] <- tweetscores::estimateIdeology2(user = user_metadata$user_id[i],
                                                     friends = (friends_df %>% 
                                                                  filter(user==user_metadata$user_id[i]) %>%
                                                                  .$user_id),
                                                     replace_outliers = TRUE,
                                                     verbose = FALSE))
  pb$tick()
}

user_metadata <- user_metadata %>%
  mutate(barbera_scores = unlist(barbera_scores_list)) %>%
  mutate(barbera_scores_NAtoZero = ifelse(is.na(barbera_scores), 0, barbera_scores))
```


```{r}
#estimateIdeology MLE DOESN'T WORK

barbera_scores_list_MLE <- list()

pb <- progress::progress_bar$new(format = "  estimating [:bar] :percent eta: :eta", total = nrow(user_metadata), clear = FALSE)
for (i in 1:nrow(user_metadata)) {
  barbera_scores_list_MLE[[i]] <- c("beta" = NA, "theta" = NA)
  samples <- NA
  try(samples <- tweetscores::estimateIdeology(user = user_metadata$user_id[i],
                                                     friends = (friends_df %>% 
                                                                  filter(user==user_metadata$user_id[i]) %>%
                                                                  .$user_id),
                                                     method = "MLE",
                                                     verbose = FALSE)$samples)
  try(barbera_scores_list_MLE[[i]] <- c("beta" = mean(samples[,2,2]), "theta" = mean(samples[,2,1])))
  pb$tick()
}

barbera_scores_MLE<- t(simplify2array(barbera_scores_list_MLE, higher = TRUE))
```


```{r}
colnames(barbera_scores_MLE)
hist(barbera_scores_MLE[,1])
hist(barbera_scores_MLE[,2])


plot(barbera_scores_MLE[,1], user_metadata$barbera_scores_NAtoZero, ylab = "Correspondence Ideology", xlab = "MLE Political Interest")

plot(barbera_scores_MLE[,2], user_metadata$barbera_scores_NAtoZero, ylab = "Correspondence Ideology", xlab = "MLE Ideology")
#this doesn't make sense, don't use it
```

# approximate political interest

```{r}
tweetscores::estimateIdeology2

#tweetscores::refdataCA
str(tweetscores::refdataCA)
str(tweetscores::refdataCA$id)

reference_ids <- tweetscores::refdataCA$id
length(reference_ids)

prop_accts_in_barbera <- friends_df %>%
  group_by(user) %>%
  summarise(prop_accts_in_barbera = mean(user_id %in% reference_ids),
            sum_accts_in_barbera = sum(user_id %in% reference_ids)) %>%
  rename(user_id = user)



user_metadata <- left_join(user_metadata %>% select(-c(prop_accts_in_barbera, sum_accts_in_barbera, prop_barbera_in_accts, sum_barbera_in_accts)), prop_accts_in_barbera)

plot(user_metadata$barbera_scores_NAtoZero, user_metadata$prop_accts_in_barbera)
plot(user_metadata$barbera_scores_NAtoZero, user_metadata$sum_accts_in_barbera)

plot(user_metadata$barbera_scores_NAtoZero, log10(user_metadata$prop_accts_in_barbera))
plot(user_metadata$barbera_scores_NAtoZero, log10(user_metadata$sum_accts_in_barbera))

plot((user_metadata$sum_accts_in_barbera), (user_metadata$prop_accts_in_barbera))
plot(log10(user_metadata$sum_accts_in_barbera), log10(user_metadata$prop_accts_in_barbera))

# plot(log10(user_metadata$friends_count), log10(user_metadata$prop_accts_in_barbera))
# plot(log10(user_metadata$sum_accts_in_barbera), log10(user_metadata$prop_accts_in_barbera))
```




```{r}
hist(user_metadata$barbera_scores, breaks = cSeq(-4,4,.25))
quantiles_a <- quantile(user_metadata$barbera_scores, na.rm = T, probs = seq(.1,.9,.1))
abline(v=quantiles_a, col = plotGradient(input = c(1,2,3,4,5,4,3,2,1), left_color = c(.1,.8,.1,.8), right_color = c(.1,.2,.1,.8)))
par(xpd=T)
text(x = quantiles_a, y = 0, labels = names(quantiles_a), pos = 1, offset = 1, cex = .9)
par(xpd=F)

hist(user_metadata$barbera_scores_NAtoZero, breaks = cSeq(-4,4,.25))
quantiles_b <- quantile(user_metadata$barbera_scores_NAtoZero, probs = seq(.1,.9,.1))
abline(v=quantiles_b, col = plotGradient(input = c(1,2,3,4,5,4,3,2,1), left_color = c(.1,.8,.1,.8), right_color = c(.1,.2,.1,.8)))
par(xpd=T)
text(x = quantiles_b, y = 0, labels = names(quantiles_b), pos = 1, offset = 1, cex = .9)

```


```{r}
user_metadata <- user_metadata %>% mutate(follower_friend_ratio = followers_count/friends_count,
                                          friend_follower_ratio = friends_count/followers_count)

```



```{r}
hist(user_metadata$follower_friend_ratio, breaks = 10000, xlim = c(0,500))
hist(user_metadata$friend_follower_ratio, breaks = 100)


quantile(user_metadata$friend_follower_ratio, prob = .2)
```

```{r}
user_metadata %>% filter(barbera_scores_NAtoZero<quantile(barbera_scores_NAtoZero, .25)) %>%
  filter(friend_follower_ratio<.5 & friend_follower_ratio>.2) %>%
  transmute(text, screen_name, description, followers_count, friends_count, barbera_scores_NAtoZero) %>%
  arrange((followers_count))


user_metadata %>% #filter(barbera_scores_NAtoZero<quantile(barbera_scores_NAtoZero, .25)) %>%
  filter(friend_follower_ratio<.5 & friend_follower_ratio>.2) %>%
  transmute(screen_name, followers_count, friends_count, barbera_scores_NAtoZero) %>%
  arrange(desc(followers_count))


user_metadata %>% filter(barbera_scores_NAtoZero<quantile(barbera_scores_NAtoZero, .1)) %>%
  filter(friend_follower_ratio<.5) %>%
  filter(verified == FALSE) %>%
  transmute(screen_name, followers_count, friends_count, barbera_scores_NAtoZero) %>%
  arrange(desc(followers_count))
```


```{r}
library(tricordR)
library(rtweet)

test_scrape <- user_metadata %>% filter(followers_count < 50000) %>% sample_n(18)

test <- getFollowersBig(users = test_scrape$user_id, n = 500000, list_tokens = prepTokens("ws_tw"))
```




```{r}
user_metadata %>% filter(barbera_scores_NAtoZero<quantile(barbera_scores_NAtoZero, .1)) %>%
  transmute(user_id, screen_name, followers_count, friends_count, barbera_scores_NAtoZero) %>%
  arrange(desc(followers_count))

user_metadata %>% filter(barbera_scores_NAtoZero<quantile(barbera_scores_NAtoZero, .2)) %>%
  transmute(user_id, screen_name, followers_count, friends_count, barbera_scores_NAtoZero) %>%
  arrange(desc(followers_count))

user_metadata %>% filter(barbera_scores_NAtoZero<quantile(barbera_scores_NAtoZero, .3)) %>%
  transmute(user_id, screen_name, followers_count, friends_count, barbera_scores_NAtoZero) %>%
  arrange(desc(followers_count))
```


```{r}
barbera_threshold <- .1
followers_max <- 50000
friend_follower_ratio_max <- .5

quantile(user_metadata$barbera_scores_NAtoZero, .1)

user_metadata_filtered <- user_metadata %>% filter(barbera_scores_NAtoZero<quantile(barbera_scores_NAtoZero, barbera_threshold)) %>% 
  filter(followers_count<followers_max) %>%
  filter(friend_follower_ratio<friend_follower_ratio_max) %>%
  transmute(user_id, screen_name, followers_count, friends_count, barbera_scores_NAtoZero) %>%
  arrange(desc(followers_count))

nrow(user_metadata_filtered)/nrow(user_metadata)

user_metadata_filtered
```



```{r}
historical_timelines <- getTimelinesHistorical(user_metadata_filtered$user_id, list_tokens = prepTokens("ws_tw"))
historical_timelines <- historical_timelines[[1]]
```


```{r}
library(darmoc)

preds <- darmoc::darmocClassify(historical_timelines$text)
historical_timelines <- historical_timelines %>% mutate(darmoc_ideo = preds[,1],
                                                        darmoc_sure = preds[,2],
                                                        darmoc_crossed = darmoc_ideo*darmoc_sure)
```


```{r}
darmoc_scores <- historical_timelines %>% group_by(user_id) %>% summarise(darmoc_mean = mean(darmoc_crossed))

user_metadata_filtered <- left_join(user_metadata_filtered, darmoc_scores)
```


```{r}
par(pty="s")
plot(user_metadata_filtered$barbera_scores_NAtoZero, user_metadata_filtered$darmoc_mean)

```


```{r}
user_metadata_filtered %>% arrange(darmoc_mean)

```



```{r}


```



#######################



```{r}
#estimateIdeology2

friends_df <- readRDS("~/tricordings/studies/spirals_assignment_sampling/2_friends_scraped/friends_20210707160849.rds")
user_metadata <- lookup_users(users = unique(friends_df$user), token = prepTokens("ws_tw")[[1]])


pb <- progress::progress_bar$new(
  format = "  estimating [:bar] :percent eta: :eta",
  total = nrow(user_metadata), clear = FALSE)

for (i in 1:nrow(user_metadata)) {
  try(user_metadata$barbera_score[i] <- tweetscores::estimateIdeology2(user = user_metadata$user_id[i],
                                                                       friends = (friends_df %>% 
                                                                                    filter(user==user_metadata$user_id[i]) %>%
                                                                                    .$user_id)))
  pb$tick()
}

sum(is.na(user_metadata$barbera_score))
hist(user_metadata$barbera_score, breaks = cSeq(-4,4,.5))

# user_metadata$barbera_score_nazero <- user_metadata$barbera_score
# user_metadata$barbera_score_nazero[which(is.na(user_metadata$barbera_score_nazero))] <- 0
```



```{r}
#estimateIdeology MLE

friends_df <- readRDS("~/tricordings/studies/spirals_assignment_sampling/2_friends_scraped/friends_20210707160849.rds")
user_metadata <- lookup_users(users = unique(friends_df$user), token = prepTokens("ws_tw")[[1]])

hist(user_metadata$followers_count)

pb <- progress::progress_bar$new(
  format = "  estimating [:bar] :percent eta: :eta",
  total = nrow(user_metadata), clear = FALSE)

barbera_scores <- list()

for (i in 1:nrow(user_metadata)) {
  barbera_score <- c(NA, NA)
  try(barbera_score <- tweetscores::estimateIdeology(user = user_metadata$user_id[i],
                                                     friends = (friends_df %>% 
                                                                                    filter(user==user_metadata$user_id[i]) %>%
                                                                                    .$user_id),
                                                     method = "MLE",
                                                     verbose = FALSE)$Rhat)
  barbera_scores[[i]] <- barbera_score
  pb$tick()
}


barbera_scores <- do_call_rbind(barbera_scores)
hist((barbera_scores[,1]))
hist((barbera_scores[,2]))

# user_metadata$barbera_interest <- barbera_scores[,1]
# user_metadata$barbera_ideology <- barbera_scores[,2]
```

```{r}
# #estimateIdeology MCMC [DOESN'T WORK AT ALL!  ERROR MESSAGE "data length [150] is not a sub-multiple or multiple of the number of rows [5000]" FILLS THE CONSOLE!]
# 
# friends_df <- readRDS("~/tricordings/studies/spirals_assignment_sampling/2_friends_scraped/friends_20210707160849.rds")
# user_metadata <- lookup_users(users = unique(friends_df$user), token = prepTokens("ws_tw")[[1]])
# 
# hist(user_metadata$followers_count)
# 
# pb <- progress::progress_bar$new(
#   format = "  estimating [:bar] :percent eta: :eta",
#   total = nrow(user_metadata), clear = FALSE)
# 
# barbera_scores <- list()
# 
# for (i in 1:nrow(user_metadata)) {
#   barbera_score <- c(NA, NA)
#   try(barbera_score <- tweetscores::estimateIdeology(user = user_metadata$user_id[i],
#                                                      friends = (friends_df %>% 
#                                                                                     filter(user==user_metadata$user_id[i]) %>%
#                                                                                     .$user_id),
#                                                      method = "MCMC",
#                                                      verbose = FALSE)$Rhat)
#   barbera_scores[[i]] <- barbera_score
#   pb$tick()
# }
# 
# 
# barbera_scores <- do_call_rbind(barbera_scores)
# hist((barbera_scores[,1]))
# hist((barbera_scores[,2]))
# 
# # user_metadata$barbera_interest <- barbera_scores[,1]
# # user_metadata$barbera_ideology <- barbera_scores[,2]
```


```{r}
#estimateIdeology2
friends_df_1 <- readRDS("~/tricordings/studies/spirals_assignment_sampling/2_friends_scraped/friends_20210707160849.rds")
user_metadata_1 <- lookup_users(users = unique(friends_df_1$user), token = prepTokens("ws_tw")[[1]])
pb <- progress::progress_bar$new(format = "  estimating [:bar] :percent eta: :eta", total = nrow(user_metadata_1), clear = FALSE)

for (i in 1:nrow(user_metadata_1)) {
  try(user_metadata_1$barbera_score[i] <- tweetscores::estimateIdeology2(user = user_metadata_1$user_id[i],
                                                                       friends = (friends_df_1 %>% 
                                                                                    filter(user==user_metadata_1$user_id[i]) %>%
                                                                                    .$user_id),
                                                     replace_outliers = TRUE,
                                                     verbose = FALSE))
  pb$tick()
}
hist(user_metadata_1$barbera_score, breaks = cSeq(-4,4,.5))
length(user_metadata_1$barbera_score)

user_metadata_1
```



```{r}
#estimateIdeology2 GOOD
friends_df <- readRDS("~/tricordings/studies/spirals_assignment_sampling/2_friends_scraped/friends_20210707160849.rds")
user_metadata <- lookup_users(users = unique(friends_df$user), token = prepTokens("ws_tw")[[1]])
barbera_scores <- list()
pb <- progress::progress_bar$new(
  format = "  estimating [:bar] :percent eta: :eta",
  total = nrow(user_metadata), clear = FALSE)

for (i in 1:nrow(user_metadata)) {
  barbera_score <- NA
  try(barbera_score <- tweetscores::estimateIdeology2(user = user_metadata$user_id[i],
                                                     friends = (friends_df %>% 
                                                                  filter(user==user_metadata$user_id[i]) %>%
                                                                  .$user_id),
                                                     replace_outliers = TRUE,
                                                     verbose = FALSE))
  barbera_scores[[i]] <- barbera_score
  pb$tick()
}

barbera_scores_v <- unlist(barbera_scores)
hist(barbera_scores_v, breaks = cSeq(-4,4,.5))
```







```{r}




```


```{r}


```


```{r}


```


```{r}


```


#############

WHY ARE THESE DIFFERENT???????  unclear.... giving up

```{r}
#estimateIdeology2
friends_df <- readRDS("~/tricordings/studies/spirals_assignment_sampling/2_friends_scraped/friends_20210707160849.rds")
user_metadata <- lookup_users(users = unique(friends_df$user), token = prepTokens("ws_tw")[[1]]) %>% mutate(barbera_score = NA)

barbera_scores <- list()
barbera_scores2 <- list()

pb <- progress::progress_bar$new(format = "  estimating [:bar] :percent eta: :eta", total = nrow(user_metadata), clear = FALSE)
for (i in 1:nrow(user_metadata)) {
  try(user_metadata$barbera_score[i] <- tweetscores::estimateIdeology2(user = user_metadata$user_id[i],
                                                                       friends = (friends_df %>% 
                                                                                    filter(user==user_metadata$user_id[i]) %>%
                                                                                    .$user_id),
                                                                       replace_outliers = FALSE,
                                                                       verbose = FALSE))
  
  try(barbera_scores[[i]] <- tweetscores::estimateIdeology2(user = user_metadata$user_id[i],
                                                            friends = (friends_df %>% 
                                                                         filter(user==user_metadata$user_id[i]) %>%
                                                                         .$user_id),
                                                            replace_outliers = FALSE,
                                                            verbose = FALSE))
  
  try(barbera_scores2[[i]] <- tweetscores::estimateIdeology2(user = user_metadata$user_id[i],
                                                                       friends = (friends_df %>%
                                                                                    filter(user==user_metadata$user_id[i]) %>%
                                                                                    .$user_id),
                                                             replace_outliers = FALSE,
                                                             verbose = FALSE))
  
  # user_metadata$barbera_score[i] <- barbera_score
  # barbera_scores[[i]] <- barbera_score
  pb$tick()
}

mean(user_metadata$barbera_score, na.rm = T)
mean(unlist(barbera_scores), na.rm = T)

hist(user_metadata$barbera_score, breaks = cSeq(-4,4,.5))
hist(unlist(barbera_scores), breaks = cSeq(-4,4,.5))
hist(unlist(barbera_scores2), breaks = cSeq(-4,4,.5))


```








##################################




```{r}
tokens <- prep_tokens("ws_tw", 1:9)

start <- Sys.time()

while (as.numeric(difftime(Sys.time(), start, units = "mins")) < 240){
  print(paste0(round(as.numeric(difftime(Sys.time(), start, units = "mins")), 1), " mins elapsed"))
  streamed_tweets <- stream_tweets(c(-125, 26, -65, 49), timeout = 120, token = tokens[[1]])
  filtered_users <- streamed_tweets %>% filter(country_code=="US", lang=="en", followers_count>5000) %>% distinct(user_id, .keep_all = T) %>% pull(user_id)
  editGroup(group_name = "us_en_5k", study_name = "assignment_sampling", add_users = filtered_users, tokens = tokens, first_scrape = T)
}
```




